// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompilePack(arg1) {
  return window['go']['main']['App']['CompilePack'](arg1);
}

export function GetData(arg1) {
  return window['go']['main']['App']['GetData'](arg1);
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetUserSetting() {
  return window['go']['main']['App']['GetUserSetting']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function NotifyText(arg1) {
  return window['go']['main']['App']['NotifyText'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function SaveUserSetting(arg1) {
  return window['go']['main']['App']['SaveUserSetting'](arg1);
}

export function SelfVersion() {
  return window['go']['main']['App']['SelfVersion']();
}

export function UpdateScriptVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateScriptVersion'](arg1, arg2, arg3);
}
