// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompilePack(arg1:string):Promise<string>;

export function EmitMessageToNormalizePanel(arg1:string):Promise<void>;

export function GetData():Promise<string>;

export function GetUserSetting():Promise<string>;

export function Normalize(arg1:string,arg2:string):Promise<string>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function NotifyText(arg1:string):Promise<void>;

export function OpenDirectoryDialogCall():Promise<string>;

export function SaveUserSetting(arg1:string):Promise<void>;

export function SelfVersion():Promise<string>;

export function UninstallApp():Promise<string>;

export function UpdateScriptVersion(arg1:string,arg2:string):Promise<string>;
