// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoUpdate(arg1:string):Promise<string>;

export function CompilePack(arg1:string):Promise<void>;

export function EmitMessageToNormalizePanel(arg1:string):Promise<void>;

export function GetData(arg1:boolean):Promise<string>;

export function GetImage(arg1:string):Promise<string>;

export function GetUserSetting():Promise<string>;

export function Normalize(arg1:string,arg2:string):Promise<string>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function NotifyText(arg1:string):Promise<void>;

export function OpenDirectoryDialog(arg1:any):Promise<string>;

export function SaveUserSetting(arg1:string):Promise<void>;

export function SelfVersion():Promise<string>;

export function UpdateScriptVersion(arg1:string,arg2:string,arg3:string):Promise<void>;
