// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompilePack(arg1) {
  return window['go']['main']['App']['CompilePack'](arg1);
}

export function EmitMessageToNormalizePanel(arg1) {
  return window['go']['main']['App']['EmitMessageToNormalizePanel'](arg1);
}

export function GetData() {
  return window['go']['main']['App']['GetData']();
}

export function GetUserSetting() {
  return window['go']['main']['App']['GetUserSetting']();
}

export function Normalize(arg1, arg2) {
  return window['go']['main']['App']['Normalize'](arg1, arg2);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function NotifyText(arg1) {
  return window['go']['main']['App']['NotifyText'](arg1);
}

export function OpenDirectoryDialogCall() {
  return window['go']['main']['App']['OpenDirectoryDialogCall']();
}

export function SaveUserSetting(arg1) {
  return window['go']['main']['App']['SaveUserSetting'](arg1);
}

export function SelfVersion() {
  return window['go']['main']['App']['SelfVersion']();
}

export function UninstallApp() {
  return window['go']['main']['App']['UninstallApp']();
}

export function UpdateScriptVersion(arg1, arg2) {
  return window['go']['main']['App']['UpdateScriptVersion'](arg1, arg2);
}
